# Generated by Django 6.0 on 2026-08-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_player_location_sound_artist_legacy_alter_player_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cosound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cosound')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listener')),
            ],
        ),
    ]
